[versions]

java = "17"

jbpl = "1.0.0"
ow2asm = "9.8" # https://gitlab.ow2.org/asm/asm/-/tags
karmaConventions = "1.7.0" # https://github.com/karmakrafts/karma-conventions/tags
gradleNexus = "2.0.0" # https://github.com/gradle-nexus/publish-plugin/releases
antlr = "4.13.2" # https://github.com/antlr/antlr4/releases
annotations = "26.0.2" # https://github.com/JetBrains/java-annotations/releases
junit = "5.13.4" # https://github.com/junit-team/junit-framework/releases
junitPlatform = "1.13.4" # https://mvnrepository.com/artifact/org.junit.platform/junit-platform-launcher
jansi = "3.30.6"
shadow = "9.2.2"

[libraries]

antlr = { module = "org.antlr:antlr4", version.ref = "antlr" }
antlr-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
ow2-asm-core = { module = "org.ow2.asm:asm", version.ref = "ow2asm" }
ow2-asm-tree = { module = "org.ow2.asm:asm-tree", version.ref = "ow2asm" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
jansi = { module = "org.jline:jline-terminal-jansi", version.ref = "jansi" }

[plugins]

karmaConventions = { id = "dev.karmakrafts.conventions.karma-conventions", version.ref = "karmaConventions" }
gradleNexus = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "gradleNexus" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }